import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import test from 'node:test';
import { createMiddlewareRuntime, sha256 } from '../../sdk/typescript/dist/middleware/index.js';
import { startRuntime } from './runtime-fixture.mjs';

test('TypeScript and real Python sync/async clients share exact durable replacements and recovery pages', { timeout:30000 }, async t => {
  const service=await startRuntime();t.after(service.stop);
  const runtime=createMiddlewareRuntime({endpoint:service.endpoint});t.after(()=>runtime.close());await runtime.ready();
  const scope={namespace:'client-parity',session_id:'conversation',branch_id:'main',cache_epoch:'0'};
  const adapter={id:'parity',version:'1',framework_version:'1',serialization_revision:'parity-v1'};
  const content=Array.from({length:150},(_,i)=>`[INFO] café 🌍 source row ${i} original bytes and verbose details\r\n`).join('');
  const candidate={id:'tool-1',source_id:'document-1',content};
  const manifest=[{id:'message-0',sha256:await sha256(content)}];
  const result=await runtime.optimize({scope,adapter,manifest,candidates:[{id:candidate.id,sourceId:candidate.source_id,content}],binding:runtime.recovery(scope)});
  assert.equal(result.status,'optimized',result.reason);
  const path=join(service.home,'client-parity.json');
  await writeFile(path,JSON.stringify({endpoint:service.endpoint,scope,adapter,candidate,manifest,replacement:result.replacements[0].text}));
  const script=fileURLToPath(new URL('./client-parity.py',import.meta.url));
  const sdk=fileURLToPath(new URL('../../sdk/python',import.meta.url));
  const {stdout}=await promisify(execFile)('python3',[script,path],{env:{...process.env,PYTHONPATH:sdk},timeout:20000,maxBuffer:65536});
  const evidence=JSON.parse(stdout);
  assert.equal(evidence.original_sha256,await sha256(content));
  assert.equal(evidence.replacement_sha256,result.replacements[0].sha256);
  assert.ok(evidence.pages>1);
  t.diagnostic(JSON.stringify(evidence));
});
