/** Native runtime provenance from Go's actual compiled/embedded input closure. */
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile, readdir, mkdir, mkdtemp, writeFile, realpath } from 'node:fs/promises';
import { resolve, relative, dirname, sep } from 'node:path';
import { pathToFileURL } from 'node:url';
import { tmpdir } from 'node:os';
import { root } from './inventory.mjs';

const targets = Object.freeze({ proxy: './proxy/cmd/caveman-proxy', mcp: './mcp/cmd/caveman-mcp', 'middleware-tests': './proxy/internal/middleware' });
const testTarget = target => target === 'middleware-tests';
const inputFields = ['GoFiles', 'CgoFiles', 'CFiles', 'CXXFiles', 'MFiles', 'HFiles', 'FFiles', 'SFiles', 'SwigFiles', 'SwigCXXFiles', 'SysoFiles', 'EmbedFiles'];
const encode = value => `${JSON.stringify(value, null, 2)}\n`;
const sha = value => createHash('sha256').update(value).digest('hex');
const fail = message => { throw new Error(`Runtime build refused: ${message}`); };
const outside = value => value === '..' || value.startsWith(`..${sep}`) || value.startsWith(sep);
const hashPattern = /^[a-f0-9]{64}$/;

export function parseGoPackages(text) {
  const values = [];
  let start = -1, depth = 0, quoted = false, escaped = false;
  for (let index = 0; index < text.length; index++) {
    const char = text[index];
    if (start < 0) {
      if (/\s/.test(char)) continue;
      if (char !== '{') fail('malformed Go package stream');
      start = index; depth = 1; continue;
    }
    if (quoted) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') quoted = false;
    } else if (char === '"') quoted = true;
    else if (char === '{' || char === '[') depth++;
    else if (char === '}' || char === ']') {
      if (--depth === 0) { values.push(JSON.parse(text.slice(start, index + 1))); start = -1; }
    }
  }
  if (start >= 0 || !values.length) fail('incomplete Go package stream');
  return values;
}

async function repositoryInput(path) {
  if (typeof path !== 'string' || path.startsWith('/') || path.includes('\\') || path.split('/').some(part => !part || part === '.' || part === '..')) fail(`invalid owned input ${path}`);
  const actual = await realpath(resolve(root, path));
  if (outside(relative(root, actual))) fail(`owned input escaped repository: ${path}`);
  return { path, role: 'runtime_source', sha256: sha(await readFile(actual)) };
}

export async function runtimeSourcesFromPackages(packages) {
  const selected = new Set(['go.mod', 'go.sum']);
  const modules = new Map(), ownedPackages = [], generated = [];
  for (const item of packages) {
    if (item.Error || item.DepsErrors?.length || item.Incomplete) fail(`unresolved dependency ${item.ImportPath}`);
    if (item.Module && !item.Module.Main) {
      const module = item.Module.Replace ?? item.Module;
      if (!module.Version || !module.Sum) fail(`unversioned or unchecked external module ${module.Path}`);
      modules.set(module.Path, { path: module.Path, version: module.Version, sum: module.Sum, go_mod_sum: module.GoModSum ?? null });
    }
    if (!item.Dir) continue;
    const directory = await realpath(item.Dir), rel = relative(root, directory);
    if (outside(rel)) {
      if (item.Module?.Main || item.Module?.Replace && !item.Module.Replace.Version) fail(`local module outside repository: ${item.ImportPath}`);
      continue;
    }
    const names = [...new Set(inputFields.flatMap(field => item[field] ?? []))].sort();
    if (!names.length) fail(`owned package has no selected inputs: ${item.ImportPath}`);
    for (const name of names) {
      const path = resolve(directory, name), owned = relative(root, path);
      if (outside(owned)) {
        const bytes = await readFile(path);
        if (item.Name !== 'main' || !item.ImportPath.endsWith('.test') || !bytes.toString('utf8').trimStart().startsWith('// Code generated by \'go test\'. DO NOT EDIT.')) fail(`unowned generated build input: ${path}`);
        generated.push({ package: item.ImportPath, path, sha256: sha(bytes) });
      } else selected.add(owned.split(sep).join('/'));
    }
    ownedPackages.push({ import_path: item.ImportPath, directory: rel.split(sep).join('/'), inputs: names,
      imports: [...(item.Imports ?? [])].sort() });
  }
  if (!ownedPackages.length) fail('Go returned no owned packages');
  return { files: await Promise.all([...selected].sort().map(repositoryInput)),
    packages: ownedPackages.sort((a, b) => a.import_path.localeCompare(b.import_path)),
    external_modules: [...modules.values()].sort((a, b) => a.path.localeCompare(b.path)),
    ...(generated.length ? { generated_sources: generated.sort((a, b) => a.path.localeCompare(b.path)) } : {}) };
}

function nativeEnvironment(output) {
  const env = Object.fromEntries(Object.entries(process.env).filter(([name]) =>
    !/(?:API_KEY|ACCESS_TOKEN|AUTH_TOKEN|CLIENT_SECRET|SECRET_ACCESS_KEY|SESSION_TOKEN|GOOGLE_APPLICATION_CREDENTIALS|AWS_PROFILE)/i.test(name)));
  const os = { darwin: 'darwin', linux: 'linux', win32: 'windows' }[process.platform];
  const arch = { arm64: 'arm64', x64: 'amd64' }[process.arch];
  if (!os || !arch) fail(`unqualified native build platform ${process.platform}/${process.arch}`);
  return { ...env, GOOS: os, GOARCH: arch, GOFLAGS: '', GOWORK: 'off',
    GOCACHE: process.env.CAVEMAN_MIDDLEWARE_BUILD_GOCACHE ?? process.env.GOCACHE ?? resolve(output, 'go-cache'),
    GOTMPDIR: resolve(output, 'go-tmp') };
}

async function command(program, args, { env, output, name, timeout = 900_000 }) {
  let text = '', exceeded = false;
  const result = await new Promise((yes, no) => {
    const child = spawn(program, args, { cwd: root, env, stdio: ['ignore', 'pipe', 'pipe'] });
    const timer = setTimeout(() => { exceeded = true; child.kill('SIGTERM'); }, timeout);
    const capture = chunk => { text += chunk; if (text.length > 64 * 1024 * 1024) { exceeded = true; child.kill('SIGTERM'); } };
    child.stdout.on('data', capture); child.stderr.on('data', capture);
    child.on('error', error => { clearTimeout(timer); no(error); });
    child.on('close', code => { clearTimeout(timer); yes(code); });
  });
  const path = resolve(output, `${name}.log`);
  await writeFile(path, text);
  const record = { program, args, cwd: '.', exit_code: result, exceeded, raw_output: { path, sha256: sha(text) } };
  if (result !== 0 || exceeded) { const error = new Error(`Runtime build refused: ${name} failed (exit ${result}); ${path}`); error.command = record; throw error; }
  return { record, text };
}

/** Run go list against exact native build flags; no guessed filesystem globs. */
export async function captureRuntimeClosure({ target = 'proxy', output, go = process.env.CAVEMAN_MIDDLEWARE_GO ?? 'go', env = nativeEnvironment(output), name = 'dependencies' }) {
  if (!targets[target]) fail(`unknown target ${target}`);
  await mkdir(output, { recursive: true });
  await mkdir(env.GOCACHE, { recursive: true }); await mkdir(env.GOTMPDIR, { recursive: true });
  const listed = await command(go, ['list', '-mod=readonly', '-deps', ...(testTarget(target) ? ['-test'] : []), '-json', targets[target]], { env, output, name });
  const closure = await runtimeSourcesFromPackages(parseGoPackages(listed.text));
  return { target: targets[target], ...closure, manifest_sha256: sha(encode(closure)), command: listed.record };
}

/** A new native binary, with complete owned inputs snapshotted before and after. */
export async function buildRuntime({ target = 'proxy', output, go = process.env.CAVEMAN_MIDDLEWARE_GO ?? 'go' }) {
  if (!output || !targets[target]) fail('explicit output and allowed target are required');
  output = resolve(output);
  if ((await readdir(output).catch(error => { if (error.code === 'ENOENT') return []; throw error; })).length) fail('output must be empty');
  await mkdir(output, { recursive: true });
  const env = nativeEnvironment(output);
  await mkdir(env.GOCACHE, { recursive: true }); await mkdir(env.GOTMPDIR, { recursive: true });
  const commands = [], report = { schema_version: 1, producer: 'caveman-middleware-runtime-build-v1', evidence_class: 'native_runtime_build', recorded_at: new Date().toISOString(),
    target: targets[target], tests: testTarget(target), native: { platform: process.platform, arch: process.arch }, commands, completed: false };
  try {
    const environment = await command(go, ['env', '-json', 'GOVERSION', 'GOROOT', 'GOOS', 'GOARCH', 'CGO_ENABLED', 'GOAMD64', 'GOARM64', 'GOEXPERIMENT', 'GOFLAGS', 'GOMOD', 'GOWORK', 'CC', 'CXX'], { env, output, name: 'go-environment' });
    commands.push(environment.record); report.toolchain = JSON.parse(environment.text);
    if (report.toolchain.GOOS !== env.GOOS || report.toolchain.GOARCH !== env.GOARCH || report.toolchain.GOMOD !== resolve(root, 'go.mod') || report.toolchain.GOWORK !== 'off') fail('Go build is not native or uses another module/workspace');
    const toolchainFiles = ['bin/go', `pkg/tool/${env.GOOS}_${env.GOARCH}/compile`, `pkg/tool/${env.GOOS}_${env.GOARCH}/link`];
    if (report.toolchain.CGO_ENABLED === '1') toolchainFiles.push(`pkg/tool/${env.GOOS}_${env.GOARCH}/cgo`);
    report.toolchain_hashes = await Promise.all(toolchainFiles.map(async name => { const path = resolve(report.toolchain.GOROOT, name); return { path, sha256: sha(await readFile(path)) }; }));
    const before = await captureRuntimeClosure({ target, output, go, env, name: 'dependencies-before' });
    report.before = before; commands.push(before.command);
    commands.push((await command(go, ['mod', 'verify'], { env, output, name: 'module-verification-before' })).record);
    const binary = resolve(output, target === 'proxy' ? 'caveman-proxy' : target === 'mcp' ? 'caveman-mcp' : 'middleware.test');
    commands.push((await command(go, [testTarget(target) ? 'test' : 'build', ...(testTarget(target) ? ['-c'] : []), '-mod=readonly', '-p=2', '-trimpath', '-buildvcs=false', '-o', binary, targets[target]], { env, output, name: 'native-build' })).record);
    const after = await captureRuntimeClosure({ target, output, go, env, name: 'dependencies-after' });
    report.after = after; commands.push(after.command);
    commands.push((await command(go, ['mod', 'verify'], { env, output, name: 'module-verification-after' })).record);
    if (before.manifest_sha256 !== after.manifest_sha256) fail('build inputs changed while compiling');
    const metadata = await command(go, ['version', '-m', binary], { env, output, name: 'binary-metadata' });
    commands.push(metadata.record);
    report.binary = { path: binary, sha256: sha(await readFile(binary)) };
    report.source_manifest_sha256 = before.manifest_sha256;
    report.completed = true;
    report.completed_at = new Date().toISOString();
  } catch (error) { report.error = error.message; if (error.command) commands.push(error.command); throw error; }
  finally { await writeFile(resolve(output, 'build.json'), encode(report)); }
  return report;
}

/** Read-only verification. Existing success fields never supply missing inputs. */
export async function validateRuntimeBuild(reference, { binary, target = 'proxy', currentClosure } = {}) {
  if (!reference?.path || !hashPattern.test(reference.sha256 ?? '')) fail('missing build provenance reference');
  const bytes = await readFile(resolve(root, reference.path));
  if (sha(bytes) !== reference.sha256) fail('build provenance hash changed');
  const report = JSON.parse(bytes);
  if (report.producer !== 'caveman-middleware-runtime-build-v1' || report.evidence_class !== 'native_runtime_build' || report.completed !== true || report.target !== targets[target] || Boolean(report.tests) !== testTarget(target)) fail('invalid or incomplete native build provenance');
  if (!report.before?.files?.length || report.before.manifest_sha256 !== report.after?.manifest_sha256 || report.source_manifest_sha256 !== report.before.manifest_sha256) fail('missing or different before/after closure');
  for (const snapshot of [report.before, report.after]) {
    const { files, packages, external_modules } = snapshot;
    if (snapshot.manifest_sha256 !== sha(encode({ files, packages, external_modules, ...(snapshot.generated_sources ? { generated_sources: snapshot.generated_sources } : {}) })) || new Set(files.map(item => item.path)).size !== files.length) fail('tampered or duplicate runtime source closure');
    for (const file of files) if ((await repositoryInput(file.path)).sha256 !== file.sha256) fail(`stale runtime source ${file.path}`);
    if (!snapshot.command?.raw_output?.path) fail('missing actual Go dependency listing');
    const raw = await readFile(snapshot.command.raw_output.path, 'utf8');
    if (sha(raw) !== snapshot.command.raw_output.sha256) fail('tampered Go dependency listing');
    const actual = await runtimeSourcesFromPackages(parseGoPackages(raw));
    if (sha(encode(actual)) !== snapshot.manifest_sha256) fail('recorded runtime closure omits actual Go build inputs');
  }
  if (currentClosure && currentClosure.manifest_sha256 !== report.source_manifest_sha256) fail('current Go dependency closure differs from the built binary');
  if (!report.binary?.path || report.binary.sha256 !== sha(await readFile(binary ?? report.binary.path))) fail('runtime binary differs from proven native build');
  const dependencyCommands = report.commands.filter(item => item.args[0] === 'list' && item.args.includes('-deps') && item.args.at(-1) === targets[target] && item.args.includes('-test') === testTarget(target));
  if (dependencyCommands.length !== 2) fail('both actual target dependency listings are required');
  const buildCommand = report.commands.filter(item => item.args[0] === (testTarget(target) ? 'test' : 'build') && item.args.at(-1) === targets[target] && item.args.includes('-c') === testTarget(target));
  if (buildCommand.length !== 1 || !['-mod=readonly', '-trimpath', '-buildvcs=false', '-o'].every(flag => buildCommand[0].args.includes(flag)) || buildCommand[0].args[buildCommand[0].args.indexOf('-o') + 1] !== report.binary.path) fail('missing exact native target build command');
  for (const item of report.commands) {
    if (item.exit_code !== 0 || item.exceeded || !item.raw_output?.path || sha(await readFile(item.raw_output.path)) !== item.raw_output.sha256) fail('missing, failed or tampered native build command');
  }
  if (report.commands.filter(item => item.args[0] === 'mod' && item.args[1] === 'verify').length !== 2) fail('both module verifications are required');
  const expectedOS = { darwin: 'darwin', linux: 'linux', win32: 'windows' }[report.native?.platform];
  const expectedArch = { arm64: 'arm64', x64: 'amd64' }[report.native?.arch];
  if (!expectedOS || !expectedArch || report.toolchain?.GOOS !== expectedOS || report.toolchain?.GOARCH !== expectedArch) fail('build platform is not its recorded native host');
  for (const tool of report.toolchain_hashes ?? []) if (sha(await readFile(tool.path)) !== tool.sha256) fail('native Go toolchain changed');
  if (report.toolchain_hashes?.length < 3) fail('missing native compiler/linker hashes');
  return report;
}

/** Add the independently generated complete closure to a new family capture. */
export async function runtimeBuildSources({ provenance = process.env.CAVEMAN_MIDDLEWARE_RUNTIME_PROVENANCE, binary = process.env.CAVEMAN_MIDDLEWARE_TEST_BINARY, target = 'proxy' } = {}) {
  if (!provenance || !binary) fail('set the runtime provenance and matching binary before capturing a new native run');
  const path = resolve(root, provenance), reference = { path, sha256: sha(await readFile(path)) };
  const output = await mkdtemp(resolve(tmpdir(), 'caveman-runtime-closure-'));
  const env = { ...nativeEnvironment(output), GOCACHE: process.env.CAVEMAN_MIDDLEWARE_BUILD_GOCACHE ?? process.env.GOCACHE ?? resolve(dirname(path), 'go-cache') };
  const currentClosure = await captureRuntimeClosure({ target, output, env });
  const report = await validateRuntimeBuild(reference, { binary, target, currentClosure });
  return { reference, binary: report.binary, sources: report.before.files.map(({ path }) => ({ path, role: 'runtime_source' })) };
}

/** Capture new execution inputs; this never rewrites a prior run or candidate. */
export async function captureNativeCertificationInputs(options) {
  const build = await runtimeBuildSources({ binary: options.binary });
  // Replace the older guessed runtime glob with the independently built closure.
  // Test-only files outside this executable must not invalidate native proof.
  const sources = new Map(options.sources.filter(source => source.role !== 'runtime_source').map(source => [source.path, source]));
  const { requiredNativeSources } = await import('./source-scope.mjs');
  for (const source of await requiredNativeSources({ family: options.family, language: options.language, tests: [...new Set(options.tests.tests.map(test => test.file))] })) sources.set(source.path, source);
  for (const source of build.sources) sources.set(source.path, source);
  const auxiliary = [];
  if (options.family === 'F13') {
    const mcp = await runtimeBuildSources({ provenance: process.env.CAVEMAN_MCP_RUNTIME_PROVENANCE, binary: process.env.CAVEMAN_MCP_TEST_BINARY, target: 'mcp' });
    for (const source of mcp.sources) sources.set(source.path, source);
    auxiliary.push({ name: 'mcp', binary_path: mcp.binary.path, binary_sha256: mcp.binary.sha256, build_provenance: mcp.reference });
  }
  sources.set('packages/middleware/conformance/support/runtime-build.mjs', { path: 'packages/middleware/conformance/support/runtime-build.mjs', role: 'test_source' });
  const { captureCertificationInputs } = await import('./certify.mjs');
  const input = await captureCertificationInputs({ ...options, sources: [...sources.values()] });
  input.runtime.build_provenance = build.reference;
  if (auxiliary.length) input.runtime.auxiliary_builds = auxiliary;
  return input;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const args = Object.fromEntries(process.argv.slice(2).map(value => value.replace(/^--/, '').split(/=(.*)/s, 2)));
  buildRuntime({ target: args.target ?? 'proxy', output: args.output }).then(report => process.stdout.write(encode({ build: resolve(args.output, 'build.json'), binary: report.binary, inputs: report.before.files.length, source_manifest_sha256: report.source_manifest_sha256 }))).catch(error => { console.error(error.message); process.exitCode = 1; });
}
